### PR TITLE
Adjust/add auth for FX2000

### PR DESCRIPTION
**Pull request by ilikenwf**
Every other method is the same but the auth is calculated differently...which is good since my version of bcrypt isn't playing nice with ffi anyway.

I had ChatGPT do a lot of the heavy lifting here out of laziness, but it did just fine.

### CODE REVIEW

**Comment by ilikenwf** [comment]
Actually I can see this probably broke the calculation of bcrypt in your case - for whatever reason I was having issues with the bcrypt lib on my machine, though.

**Comment by ilikenwf** [comment]
Nevermind, I misread the diff.

**Comment by kylerlaird** [comment]
Thank you for the enhancement, ilikenwf.  I need to find one of my hotspots for testing.  (I don't want to use the main one and I stored the backup.)

**Comment by ilikenwf** [comment]
No problem - just handy as I can have my firewall fire off a cron job every day or so to reboot it. If I wanted to do it in a more fanciful way I guess I could build it into a full opnsense plugin with status displays and all, but meh.

**Pull request merged**
